// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoPos3.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoPos3::AutoPos3(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	std::printf("2135: Auto Pos 3 Constructor\n");
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutoPos3::Initialize() {
	std::printf("2135: Auto Pos 3 - Init\n");
}

// Called repeatedly when this Command is scheduled to run
void AutoPos3::Execute() {
	// Wait for gameData before scheduling next steps
}

// Make this return true when this Command no longer needs to run execute()
bool AutoPos3::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void AutoPos3::End() {
	std::printf("2135: Auto Pos 3 - End\n");
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoPos3::Interrupted() {
	std::printf("2135: Auto Pos 3 - Interrupted\n");
}
