// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ElevatorRun.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ElevatorRun::ElevatorRun(bool elevateDirection): frc::Command() {
    m_elevateDirection = elevateDirection;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ElevatorRun::Initialize() {
	std::printf("2135: ElevatorRun - Init\n");
	if (m_elevateDirection)
		Robot::elevator->ElevatePIDInit(0.9905*M_PI*2);
	else
		Robot::elevator->ElevatePIDInit(-0.9905*M_PI*2);


}

// Called repeatedly when this Command is scheduled to run
void ElevatorRun::Execute() {
	Robot::elevator->ElevatePIDExecute();
}

// Make this return true when this Command no longer needs to run execute()
bool ElevatorRun::IsFinished() {
    return Robot::elevator->ElevatePIDatSetPoint();
}

// Called once after isFinished returns true
void ElevatorRun::End() {
	std::printf("2135: ElevatorRun - End\n");
	Robot::elevator->ElevatePIDStop();

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ElevatorRun::Interrupted() {
	std::printf("2135: ElevatorRun - Interrupted\n");
	Robot::elevator->ElevatePIDStop();
}
