// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/Lifter.h"

Lifter::Lifter() : frc::Subsystem("Lifter") {

    std::printf("2135: LF Lifter Constructor");

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    motorLF16.reset(new WPI_TalonSRX(16));
      
    front.reset(new frc::DoubleSolenoid(0, 2, 5));
    AddChild("Front", front);
    
    back.reset(new frc::DoubleSolenoid(0, 3, 4));
    AddChild("Back", back);
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // Validate Talon SRX controller, initialize, and display firmware version
    m_talonValidLF16 = frc2135::TalonSRXUtils::TalonSRXCheck(motorLF16, "LF", "16");

    // Check if solenoids are functional or blacklisted
    if (front->IsFwdSolenoidBlackListed())
        std::printf("2135: ERROR: LF Front FWD Solenoid is BLACKLISTED\n");
    else
        std::printf("2135: LF Front FWD Solenoid is FUNCTIONAL\n");
    if (front->IsRevSolenoidBlackListed())
        std::printf("2135: ERROR: LF Front REV Solenoid is BLACKLISTED\n");
    else
        std::printf("2135: LF Front REV Solenoid is FUNCTIONAL\n");

    if (back->IsFwdSolenoidBlackListed())
        std::printf("2135: ERROR: LF Back FWD Solenoid is BLACKLISTED\n");
    else
        std::printf("2135: LF Back FWD Solenoid is FUNCTIONAL\n");
    if (back->IsRevSolenoidBlackListed())
        std::printf("2135: ERROR: LF Back REV Solenoid is BLACKLISTED\n");
    else
        std::printf("2135: LF Back REV Solenoid is FUNCTIONAL\n");

    // Retrieve lifter modified parameters from RobotConfig
     frc2135::RobotConfig* config = frc2135::RobotConfig::GetInstance();
     config->GetValueAsDouble("LF_DriveSpeed", m_driveSpeed, 0.5);

    // Set motor direction
    // Turn on Brake mode
    // Set motor peak output
    if (m_talonValidLF16) {
        motorLF16->SetInverted(true);
        motorLF16->SetNeutralMode(NeutralMode::Brake);
        motorLF16->ConfigVoltageCompSaturation(12.0, 0);
        motorLF16->EnableVoltageCompensation(true);
        
        motorLF16->ConfigPeakOutputForward(m_driveSpeed, m_timeout);
        motorLF16->ConfigPeakOutputReverse(-m_driveSpeed, m_timeout);    
    }

    Initialize();
}

void Lifter::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Lifter::Periodic() {
    // Put code here to be run every loop
    double outputLF16 = 0.0, currentLF16 = 0.0;

    if (m_talonValidLF16) {
        outputLF16 = motorLF16->GetMotorOutputVoltage();
        currentLF16 = motorLF16->GetOutputCurrent();
    }

    if (m_lifterDebug) {
        frc::SmartDashboard::PutNumber("LF_Output_LF16", outputLF16);
        frc::SmartDashboard::PutNumber("LF_Current_LF16", currentLF16);
    }
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

//////////////////////////////////////////////////////////////////////////////////

// Put methods for controlling this subsystem
// here. Call these from Commands.

void Lifter::Initialize(void) {
    std::printf("2135: LF Init\n");

    // Motor off
    if (m_talonValidLF16)
        SetLifterMotorSpeed(LIFTER_STOP);

    // Keep lifters retracted
    m_frontExtended = false;
    m_backExtended = false;
    frc::SmartDashboard::PutBoolean("LF Front Extended", m_frontExtended);
    frc::SmartDashboard::PutBoolean("LF Back Extended", m_backExtended);  
    SetFrontSolenoid(m_frontExtended);
    SetBackSolenoid(m_backExtended);  
}

void Lifter::SetLifterMotorSpeed(int direction) {
    const char *strName;
    double outputLF16 = 0.0;        // Default: off

    switch (direction)
    {
    default:
    case LIFTER_STOP:
        strName = "STOP";
        outputLF16 = 0.0;
        break;
    case LIFTER_FORWARD:
        strName = "FORWARD";
        outputLF16 = m_driveSpeed;
        break;
    case LIFTER_REVERSE:
        strName = "REVERSE";
        outputLF16 = -m_driveSpeed;
    }

    std::printf("2135: Lifter Motor Set Speed - %s\n", strName);

    if (m_talonValidLF16)
        motorLF16->Set(ControlMode::PercentOutput, outputLF16);
}

void Lifter::SetFrontSolenoid(bool extended) {
    m_frontExtended = extended;

    std::printf("2135: LF Front - %s\n", (m_frontExtended) ? "EXTEND" : "RETRACT");
    frc::SmartDashboard::PutBoolean("LF Front Extended", m_frontExtended);

    front->Set((m_frontExtended) ? front->kForward : front->kReverse);
}

void Lifter::SetBackSolenoid(bool extended) {
    m_backExtended = extended;

    std::printf("2135: LF Back - %s\n", (m_backExtended) ? "EXTEND" : "RETRACT");
    frc::SmartDashboard::PutBoolean("LF Back Extended", m_backExtended);

    back->Set((m_backExtended) ? back->kForward : back->kReverse);
}
