// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

#include "commands/ShooterRun.h"

ShooterRun::ShooterRun(int shooterSpeed, Shooter *m_shooter) :
    m_shooterSpeed(shooterSpeed),
    m_shooter(m_shooter)
{
    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("ShooterRun");
    AddRequirements(m_shooter);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
}

// Called just before this Command runs the first time
void ShooterRun::Initialize()
{
    std::printf("2135: ShooterRun - Init [%d]\n", m_shooterSpeed);
    m_shooter->SetShooterSpeed(m_shooterSpeed);
}

// Called repeatedly when this Command is scheduled to run
void ShooterRun::Execute() {}

// Make this return true when this Command no longer needs to run execute()
bool ShooterRun::IsFinished()
{
    return false;
}

// Called once after isFinished returns true
void ShooterRun::End(bool interrupted)
{
    std::printf("2135: ShooterRun - End\n");
}

bool ShooterRun::RunsWhenDisabled() const
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
