// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Transmission.h"
#include "../Robotmap.h"
#include "../Commands/ShiftHighGear.h"
Transmission::Transmission() : Subsystem("Transmission") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	shifter = RobotMap::transmissionShifter;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Transmission::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new ShiftHighGear());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
// Put methods for controlling this subsystem
// here. Call these from Commands.
//
// Enable the high gear piston
void Transmission::ShifterHigh(){
	shifter->Set( shifter->kForward );
//	RobotMap::driverStationLCD->Printf( DriverStationLCD::kUser_Line2, 0, "Gear HI " );
}
//
// Disable the high gear piston
void Transmission::ShifterLow(){
	shifter->Set( shifter->kReverse );
//	RobotMap::driverStationLCD->Printf( DriverStationLCD::kUser_Line2, 0, "Gear LO " );
}
