// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ELEVATOR_H
#define ELEVATOR_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../RobotDefaults.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Elevator: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
#if !defined (ROBORIO_STANDALONE) || defined (ROBOTBENCHTOPTEST)
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<WPI_TalonSRX> motorL7;
	std::shared_ptr<WPI_TalonSRX> motorR8;
	std::shared_ptr<frc::DigitalInput> hallLimit;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
#endif

	const int		m_slotIndex = 0;				// Motor controller profile slot index
	const int 		m_pidIndex = 0; 				// PID Slot index for sensors
	const int		m_timeout = 10;					// CAN timeout in msec to wait for response
	const double 	COUNTS_PER_ROTATION = (1024*4);	// CPR is 1024 and multipled by 4 because it is a quadrature encoder
	enum { CALIB_START, CALIB_MOVE_UP, CALIB_START_DOWN, CALIB_MOVE_DOWN, CALIB_DONE };

	double			m_targetInches;					// Target inches of height that are requested of the elevator
	double			m_targetCounts;					// Target encoder counts of height that are requested of the elevator
	bool			m_calibrated;					// Indicates whether the elevator has been calibrated
	int				m_calibrationState;				// State variable for calibration sequence
	double			m_calibrationSpeed;				// Default motor output speed during calibration
	double 			m_elevatorSpeed;				// Elevator maximum speed
	double			m_elevatorMaxHeight;
	double			m_elevatorMinHeight;

#ifdef ROBOTBENCHTOPTEST
	const double 	m_circumInches = (1.875*M_PI*2);		//Circumference in inches for Benchtop Testing
#else
	const double 	m_circumInches = (1.273*M_PI);		//Circumference in inches (Real Robot)
#endif

public:
	Elevator();
	void InitDefaultCommand() override;
	enum {ELEVATOR_STOP = 0, ELEVATOR_UP = 1, ELEVATOR_DOWN = -1};
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	double InchesToCounts(double inches);
	double CountsToInches(int counts);
	bool HallSensorIsTriggered(void);

	void MoveToPosition(double inches);
	bool MoveToPositionIsFinished(void);

	void MoveToPositionStop(void);

	void CalibrationInit(void);
	void CalibrationExecute(void);
	bool CalibrationIsFinished(void);

	void CalibrationOverride(void);

};

#endif
