// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ctre/Phoenix.h"

#include "../RobotDefaults.h"
#include "Gripper.h"
#include "../RobotMap.h"
#include "../Commands/GripperRun.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Gripper::Gripper() : frc::Subsystem("Gripper") {
	std::printf("2135: Gripper Constructor\n");

#ifdef ROBOTNOTSTANDALONE
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    motorL7 = RobotMap::gripperMotorL7;
    motorR8 = RobotMap::gripperMotorR8;
    motor9 = RobotMap::gripperMotor9;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    motorL7->SetInverted(false);
    motorR8->SetInverted(true);
    motor9->SetInverted(false); 	// TODO: Have to test this on the actual robot

    motor9->SetSelectedSensorPosition(0, pidIndex, timeout);

    motorL7->Set(ControlMode::PercentOutput, 0.0);
    motorR8->Set(ControlMode::PercentOutput, 0.0);
    motor9->Set(ControlMode::Position, 0.0);

    motorL7->SetNeutralMode(NeutralMode::Brake);
    motorR8->SetNeutralMode(NeutralMode::Brake);
    motor9->SetNeutralMode(NeutralMode::Brake);

    std::printf("2135: Motor L7 ID %d ver %d.%d\n", motorL7->GetDeviceID(), motorL7->GetFirmwareVersion()/256, motorL7->GetFirmwareVersion()%256);
    std::printf("2135: Motor R8 ID %d ver %d.%d\n", motorR8->GetDeviceID(), motorR8->GetFirmwareVersion()/256, motorR8->GetFirmwareVersion()%256);
    std::printf("2135: Motor 9 ID %d ver %d.%d\n", motor9->GetDeviceID(), motor9->GetFirmwareVersion()/265, motor9->GetFirmwareVersion()%265);

    motor9->ConfigSelectedFeedbackSensor(FeedbackDevice::CTRE_MagEncoder_Relative, pidIndex, timeout);
    motor9->SetSensorPhase(false);

    // Set power and timeout
    motor9->ConfigPeakOutputForward(102.3, timeout);
    motor9->ConfigPeakOutputReverse(-102.3, timeout);

    // Set proportional
    motor9->Config_kP(0, COUNTS_PER_ROTATION, timeout); // TODO: Set the proportional

    // Set closed loop error
    motor9->ConfigAllowableClosedloopError(0, 10, timeout);
#endif
    // Initialize Variables
    m_pidStarted = false;
}

void Gripper::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
#ifdef ROBOTNOTSTANDALONE
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        SetDefaultCommand(new GripperRun(0));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
#endif
}

void Gripper::Initialize(frc::Preferences *RobotConfig)
{
#ifdef ROBOTNOTSTANDALONE
	std::printf("2135: Gripper Init\n");
	motorL7->Set(ControlMode::PercentOutput, 0.0);
	motorR8->Set(ControlMode::PercentOutput, 0.0);
#endif

}
void Gripper::Periodic() {
    // Put code here to be run every loop

}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void Gripper::SetMotorSpeed(int speed)
{
#ifdef ROBOTNOTSTANDALONE

	double output = 0.0; 		//Default: off

	switch (speed)
	{
	default:
	case GRIPPER_STOP:
		output = 0.0;
		break;
	case GRIPPER_FORWARD:
		output = m_gripperSpeed;
		break;
	case GRIPPER_REVERSE:
		output = -m_gripperSpeed;
		break;
	}

	motorL7->Set(ControlMode::PercentOutput, output);
	motorR8->Set(ControlMode::PercentOutput, output);

#endif
}

void Gripper::ExtensionPIDInit(double angle)
{
#ifdef ROBOTNOTSTANDALONE
	std::printf("2135: Extension Started\n");

	double target;

	target = (angle * COUNTS_PER_ROTATION) / 360.0;

	// Set Encoder Position to zero
	motor9->SetSelectedSensorPosition(0, pidIndex, 0);

	// Set the mode and target
	motor9->Set(ControlMode::Position, target);

	m_pidStarted = false;
#endif
}

void Gripper::ExtensionPIDExecute(void)
{
	// No work needed because Talon does it internally
}

bool Gripper::ExtensionPIDIsAtSetpoint(void)
{
	bool pidFinished = false;

	int closedLoopError = 0;	// Initialized for ROBOTNOTSTANDALONE mode

	// Detect if closed loop error has been updates
#ifdef ROBOTNOTSTANDALONE
	closedLoopError = motor9->GetClosedLoopError(0);
	std::printf("2135: Closed loop error %d\n", closedLoopError);
	std::printf("2135: Encoder count %d\n", motor9->GetSelectedSensorPosition(0));

	double motorOutput = motor9->GetMotorOutputPercent();
	if (abs(motorOutput) >= 0.4) {
		m_pidStarted = true;
		std::printf("PID Started\n");
	}

	if (m_pidStarted == true && closedLoopError <= 20)
		pidFinished = true;
		std::printf("2135: Finished\n");
#endif
	return pidFinished;
}

void Gripper::ExtensionPIDStop(void)
{
#ifdef ROBOTNOTSTANDALONE
	std::printf("2135: Extension STOP\n");

	// Set driving mode and target
	motor9->Set(ControlMode::PercentOutput, 0.0);
#endif
}
