// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
#include "Transmission.h"
#include "../Robotmap.h"
#include "../Commands/ShiftLowGear.h"
Transmission::Transmission() : Subsystem("Transmission") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	transmissionShifter = RobotMap::transmissionTransmissionShifter;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Transmission::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new ShiftLowGear());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
// Enable the high gear piston
void Transmission::ShifterHigh(){
	transmissionShifter->Set( transmissionShifter->kForward );
	//RobotMap::driverStationLCD->Printf( DriverStationLCD::kUser_Line2, 0, "Gear HI " );
}
//
// Disable the high gear piston
void Transmission::ShifterLow(){
	transmissionShifter->Set( transmissionShifter->kReverse );
	//RobotMap::driverStationLCD->Printf( DriverStationLCD::kUser_Line2, 0, "Gear LO " );
}
