// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef CHASSIS_H
#define CHASSIS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Chassis: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Encoder* leftEncoder;
	Encoder* rightEncoder;
	SpeedController* leftMotor;
	SpeedController* rightMotor;
	RobotDrive* robotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	PIDController* driveControlLeft;
	PIDController* driveControlRight;
	Chassis();
	void InitDefaultCommand();
	void DriveUsingJoysticks(Joystick *driverStick);
	void Chassis::DriveUsingPIDInit(double distance);
	void Chassis::DriveUsingPID(void);
	void Chassis::DriveUsingPIDStop(void);
	bool Chassis::DriveUsingPIDOnTarget(void);
	void Chassis::CheesyDrive(void);
};
#endif
