// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Chassis.h"
#include "../Robotmap.h"
#include "../Commands/DriveTeleop.h"
Chassis::Chassis() : Subsystem("Chassis") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftEncoder = RobotMap::chassisLeftEncoder;
	rightEncoder = RobotMap::chassisRightEncoder;
	leftMotor = RobotMap::chassisLeftMotor;
	rightMotor = RobotMap::chassisRightMotor;
	robotDrive = RobotMap::chassisRobotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	driveControlLeft = RobotMap::driveControlLeft;
	driveControlRight = RobotMap::driveControlRight;
}
    
void Chassis::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new DriveTeleop());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
//	Normal drive during Teleop using joysticks
void Chassis::DriveUsingJoysticks(Joystick *driverStick){
	robotDrive->ArcadeDrive(driverStick, true);
}
//	Autonomous PID driving initialization
void Chassis::DriveUsingPIDInit(double distance) {
	driveControlLeft->SetSetpoint(distance);
	driveControlRight->SetSetpoint(distance);
}
//	Autonomous PID driving normal execution processing
void Chassis::DriveUsingPID(void) {
}
//	Autonomous PID driving on target check
bool Chassis::DriveUsingPIDOnTarget() {
	return (true);
}
