// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include <spdlog/fmt/ostr.h>
#include <spdlog/spdlog.h>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

#include "commands/FloorConveyorRun.h"

FloorConveyorRun::FloorConveyorRun(int conveyorDirection, FloorConveyor *m_floorconveyor) :
    m_conveyorDirection(conveyorDirection),
    m_floorconveyor(m_floorconveyor)
{
    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("FloorConveyorRun");
    AddRequirements(m_floorconveyor);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
}

// Called just before this Command runs the first time
void FloorConveyorRun::Initialize()
{
    spdlog::info("FloorConveyorRun - Init {}", m_conveyorDirection);
    m_floorconveyor->SetFloorConveyorSpeed(m_conveyorDirection);
}

// Called repeatedly when this Command is scheduled to run
void FloorConveyorRun::Execute() {}

// Make this return true when this Command no longer needs to run execute()
bool FloorConveyorRun::IsFinished()
{
    return true;
}

// Called once after isFinished returns true
void FloorConveyorRun::End(bool interrupted)
{
    spdlog::info("FloorConveyorRun - End");
}

bool FloorConveyorRun::RunsWhenDisabled() const
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
