// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Transmission.h"
#include "../Robotmap.h"
#include "../Commands/ShiftHighGear.h"
Transmission::Transmission() : Subsystem("Transmission") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	shifterSolenoid = RobotMap::transmissionShifterSolenoid;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	printf( "2135: Transmission Constructor\n" );
}
    
void Transmission::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new ShiftHighGear());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
//
//
//	Enable the high gear solenoid
//
void Transmission::ShiftHigh( void )
{
	shifterSolenoid->Set( shifterSolenoid->kForward );
	
}
//
//	Disable the high gear solenoid
//
void Transmission::ShiftLow( void )
{
	shifterSolenoid->Set( shifterSolenoid->kReverse );
}
