// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "SweeperArm.h"
#include "../Robotmap.h"
#include "../Commands/SweeperArmRetract.h"
SweeperArm::SweeperArm() : Subsystem("SweeperArm") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	extendSolenoid = RobotMap::sweeperArmExtendSolenoid;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	printf( "2135: Sweeper Arm Constructor\n" );
}
    
void SweeperArm::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new SweeperArmRetract());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
//
//	Sweeper deploy solenoid
//
void SweeperArm::Deploy( void ) 
{
	extendSolenoid->Set( extendSolenoid->kForward );
}
//
//	Sweeper retract solenoid
//
void SweeperArm::Retract( void ) 
{
	extendSolenoid->Set( extendSolenoid->kReverse );
}
