// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static Encoder* chassisEncoderL;
	static CANTalon* chassisMotorL2;
	static PIDController* chassisLeftPID;
	static CANTalon* chassisMotorL3;
	static Encoder* chassisEncoderR;
	static CANTalon* chassisMotorR4;
	static PIDController* chassisRightPID;
	static CANTalon* chassisMotorR5;
	static Ultrasonic* chassisUltrasonicDrive;
	static Encoder* hWheelEncoderH;
	static DoubleSolenoid* hWheelEngage;
	static CANTalon* hWheelMotorHL6;
	static CANTalon* hWheelMotorHR7;
	static DoubleSolenoid* intakeClamp;
	static DigitalInput* intakeToteFullIn;
	static SpeedController* intakeConveyorL;
	static SpeedController* intakeConveyorR;
	static DoubleSolenoid* stackerClamp;
	static DigitalInput* stackerToteFullIn;
	static DigitalInput* stackerToteFullOut;
	static SpeedController* stackerConveyorL;
	static SpeedController* stackerConveyorR;
	static AnalogPotentiometer* elevatorHeightPot;
	static CANTalon* elevatorMove;
	static Compressor* pneumaticsCompressor;
	static AnalogInput* pneumaticsAnalogInput1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static void init();
};
#endif
